---
- block:
  - name: DEB | Copy configuration file
    template:
      src: "{{ heartbeat_host_config_file_path }}"
      dest: "{{ heartbeat_config_file_path }}"
    notify: Restart Heartbeat

  when: ansible_os_family == 'Debian'

- block:
  - name: RH | Copy configuration file
    template:
      src: "{{ heartbeat_host_config_file_path }}"
      dest: "{{ heartbeat_config_file_path }}"
    notify: Restart Heartbeat
  when: ansible_os_family == 'RedHat'