---
- name: Include OS family specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"

- include_tasks: heartbeats_pre.yml
- include_tasks: heartbeats_install.yml

- block:
  - include_tasks: heartbeats_post.yml
  tags: heartbeat-config