heartbeat_elasticsearch_hosts: ["CHANGEME:9200"]
heartbeat_kibana_host: "CHANGEME:5601"

##  If "elastic_https_enabled" is set, you must provide username and password
heartbeat_elasticsearch_https_enabled: false
# heartbeat_elasticsearch_xpac:
  #   username: elastic
  #   password: CHANGEME
  #   protocol: https

heartbeat_custom_fields: {}
  # env: production
  # group: 
  # project:

    
heartbeat_search_config_path: "{{ playbook_dir }}/files/groups/{{ item }}/heartbeat"
heartbeat_search_config_paths: []

heartbeat_host_config_file_path: heartbeat.yml.j2
heartbeat_config_file_path: /etc/heartbeat/heartbeat.yml
heartbeat_config_path: /etc/heartbeat

heartbeat_monitors:
- type: http                                              
  name: Elasticsearch                                     
  # List or urls to query                                 
  urls: ["CHANGEME:9200"]             
  # Configure task schedule                               
  schedule: '@every 30s'                                  
                                                          
- type: icmp                                              
  name: Google Public DNS                                 
  schedule: '*/30 * * * * * *'                            
  hosts: ["CHANGEME"]                                      
                                                          
- type: tcp                                               
  schedule: '@every 5s'                                   
  hosts: ["CHANGEME:9042"]  # default TCP Echo Protocol

